run:
  timeout: 5m

linters-settings:
  errcheck:
    # HTTP response writes don't need error checking in handlers
    ignore: "fmt:.*,io/ioutil:^Read.*"

linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unused
    - gosimple
    - tagliatelle